import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL("https://hostcopy-ai.vercel.app"),
  title: "HostCopy AI — AI Airbnb & Booking.com Listing Descriptions",
  description: "Generate professional, SEO-friendly short-term rental listing descriptions in 30 seconds with AI.",
  openGraph: {
    title: "HostCopy AI — AI Airbnb & Booking.com Listing Descriptions",
    description: "One form, three ready-to-paste listings: Airbnb, Booking.com, and an Instagram caption — generated by AI in 30 seconds.",
    url: "https://hostcopy-ai.vercel.app",
    siteName: "HostCopy AI",
    type: "website",
  },
  twitter: {
    card: "summary",
    title: "HostCopy AI — AI Airbnb & Booking.com Listing Descriptions",
    description: "One form, three ready-to-paste listings: Airbnb, Booking.com, and an Instagram caption — generated by AI in 30 seconds.",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col font-sans">{children}</body>
    </html>
  );
}
