import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL("https://hostcopy-ai.vercel.app"),
  title: "HostCopy AI — AI Airbnb, Booking.com & Vacation Rental Description Generator",
  description: "Generate high-converting, professional Airbnb, Booking.com listings and Instagram captions in 30 seconds with AI. Trusted by short-term rental hosts and property managers.",
  keywords: [
    "Airbnb description generator",
    "AI Airbnb listing writer",
    "vacation rental description generator",
    "short term rental marketing",
    "Booking.com description generator",
    "property management copy tool",
    "Airbnb host AI tool",
    "vacation rental copywriting"
  ],
  authors: [{ name: "Vilius Bartainis" }],
  openGraph: {
    title: "HostCopy AI — AI Airbnb & Booking.com Listing Descriptions",
    description: "One form, three ready-to-paste listings: Airbnb, Booking.com, and an Instagram caption — generated by AI in 30 seconds.",
    url: "https://hostcopy-ai.vercel.app",
    siteName: "HostCopy AI",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "HostCopy AI — AI Airbnb & Booking.com Listing Descriptions",
    description: "One form, three ready-to-paste listings: Airbnb, Booking.com, and an Instagram caption — generated by AI in 30 seconds.",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebApplication",
              "name": "HostCopy AI",
              "url": "https://hostcopy-ai.vercel.app",
              "description": "AI-powered property description generator for Airbnb hosts, Booking.com managers, and vacation rental owners.",
              "applicationCategory": "BusinessApplication",
              "operatingSystem": "All",
              "offers": {
                "@type": "Offer",
                "price": "0",
                "priceCurrency": "EUR"
              }
            })
          }}
        />
      </head>
      <body className="min-h-full flex flex-col font-sans">{children}</body>
    </html>
  );
}
