import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import CookieConsent from "@/components/CookieConsent";
import Analytics from "@/components/Analytics";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL("https://hostcopyai.com"),
  title: "HostCopy AI — AI Airbnb, Booking.com & Vacation Rental Description Generator",
  description: "Generate high-converting, professional Airbnb, Booking.com listings and Instagram captions in 30 seconds with AI. Trusted by short-term rental hosts and property managers.",
  keywords: [
    "Airbnb description generator",
    "AI Airbnb listing writer",
    "vacation rental description generator",
    "short term rental marketing",
    "Booking.com description generator",
    "property management copy tool",
    "Airbnb host AI tool",
    "vacation rental copywriting"
  ],
  authors: [{ name: "Vilius Bartainis" }],
  openGraph: {
    title: "HostCopy AI — AI Airbnb & Booking.com Listing Descriptions",
    description: "One form, three ready-to-paste listings: Airbnb, Booking.com, and an Instagram caption — generated by AI in 30 seconds.",
    url: "https://hostcopyai.com",
    siteName: "HostCopy AI",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "HostCopy AI — AI Airbnb & Booking.com Listing Descriptions",
    description: "One form, three ready-to-paste listings: Airbnb, Booking.com, and an Instagram caption — generated by AI in 30 seconds.",
  },
  verification: {
    google: "hVKWHiD7BR0_zBOVDYrq4yo4bmf_Rhy_Nzf8CceprEk",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale} className="h-full antialiased">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500&family=Inter:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500&display=swap"
          rel="stylesheet"
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebApplication",
              "name": "HostCopy AI",
              "url": "https://hostcopyai.com",
              "description": "AI-powered property description generator for Airbnb hosts, Booking.com managers, and vacation rental owners.",
              "applicationCategory": "BusinessApplication",
              "operatingSystem": "All",
              "offers": {
                "@type": "Offer",
                "price": "0",
                "priceCurrency": "EUR",
              },
            }),
          }}
        />
      </head>
      <body className="min-h-full flex flex-col font-sans">
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
        <CookieConsent />
        <Analytics />
      </body>
    </html>
  );
}
